apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  version: 8.4.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hostpath-sc
    podTemplate:
      spec:
        nodeSelector:
          node-role: master
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
          env:
          - name: "ES_JAVA_OPTS"
            value: "-Xms2g -Xmx2g"
  - name: data
    count: 2
    config:
      node.roles: ["data", "ingest"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hostpath-sc
    podTemplate:
      spec:
        nodeSelector:
          node-role: data
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
          env:
          - name: "ES_JAVA_OPTS"
            value: "-Xms2g -Xmx2g"
