apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-master-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/es-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-master-1
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/es-master-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-slave-0
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/es-data-slave-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-slave-1
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/es-data-slave-1
