apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-primary-0
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-primary-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary-0
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-secondary-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-secondary-1
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-secondary-1
